-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.applicant_verification
(
    verification_id integer NOT NULL,
    applicant_user_id integer NOT NULL,
    PRIMARY KEY (verification_id)
);

CREATE TABLE public.applicants
(
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    nationality_id character varying(11) NOT NULL,
    date_of_birth date,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.employer_confirmation_by_system_personnel
(
    id integer NOT NULL,
    employer_user_id integer NOT NULL,
    system_personnel_user_id integer NOT NULL,
    confirmation_status boolean NOT NULL,
    confirmation_date date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employer_verification
(
    verification_id integer NOT NULL,
    employer_user_id integer NOT NULL,
    PRIMARY KEY (verification_id)
);

CREATE TABLE public.employers
(
    user_id integer NOT NULL,
    name character varying(250) NOT NULL,
    web_site character varying(50) NOT NULL,
    phone character varying(15) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.jobs
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    title character varying(50) NOT NULL,
    description character varying,
    PRIMARY KEY (id)
);

CREATE TABLE public.system_personnel
(
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(50) NOT NULL,
    password character varying(25) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.verification
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    verification_code character varying(25) NOT NULL,
    verification_status boolean NOT NULL,
    verification_date date,
    PRIMARY KEY (id)
);

ALTER TABLE public.applicant_verification
    ADD FOREIGN KEY (applicant_user_id)
    REFERENCES public.applicants (user_id)
    NOT VALID;


ALTER TABLE public.applicant_verification
    ADD FOREIGN KEY (verification_id)
    REFERENCES public.verification (id)
    NOT VALID;


ALTER TABLE public.applicants
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employer_confirmation_by_system_personnel
    ADD FOREIGN KEY (system_personnel_user_id)
    REFERENCES public.system_personnel (user_id)
    NOT VALID;


ALTER TABLE public.employer_confirmation_by_system_personnel
    ADD FOREIGN KEY (employer_user_id)
    REFERENCES public.employers (user_id)
    NOT VALID;


ALTER TABLE public.employer_verification
    ADD FOREIGN KEY (employer_user_id)
    REFERENCES public.employers (user_id)
    NOT VALID;


ALTER TABLE public.employer_verification
    ADD FOREIGN KEY (verification_id)
    REFERENCES public.verification (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.system_personnel
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;

END;